### ISSUE TITLE
What are the differences between this and the base library?

### ISSUE THREAD

**Issue by Weilin37** [markus-wa/cs-demo-minifier#11]
I noticed that this minifier library does not have many events listed in the documentation, while the base library is pretty comprehensive. Can you tell me what events are missing in this minifier?

**Comment by markus-wa** [comment]
Hey @Weilin37!

You are correct, this lib is very bare bones at the moment.

The list of available events can be found here: https://github.com/markus-wa/cs-demo-minifier/blob/master/events.md

For demoinfocs-golang the list is here: https://godoc.org/github.com/markus-wa/demoinfocs-golang/events (+all "generic" game events from here: https://github.com/markus-wa/demoinfocs-golang/blob/master/game_events.go#L102-L182)

You can add custom events something like this (untested):

```go
cfg := csminify.DefaultReplayConfig()
cfg.EventCollector.AddHandler(func(e events.WeaponFire) {
	// create an event instance when this occurs
	customEvent := replay.Event{
		Name: "custom_weapon_fire_event",
	}

	// add some attributes
	customEvent.Attributes = append(customEvent.Attributes, rep.EventAttribute{
		Key:    "my_attr",
		StrVal: "some interesting value",
	})
	customEvent.Attributes = append(customEvent.Attributes, rep.EventAttribute{
		Key:    "my_numeric_attr",
		NumVal: 123, // float64
	})

	// you can also read data from the parser
	customEvent.Attributes = append(customEvent.Attributes, rep.EventAttribute{
		Key:    "stuff from parser",
		NumVal: cfg.EventCollector.Parser().GetSomeDataFromTheParser(),
	})
	ec.AddEvent(event)
})
```

see also: https://github.com/markus-wa/cs-demo-minifier/blob/master/events.go#L68

**Comment by markus-wa** [comment]
And feel free to create pull requests or issues for any additional events you'd like to have supported.

**Comment by Weilin37** [comment]
@markus-wa  thanks so much! This is really helpful and thanks for the detailed instructions!

**Comment by markus-wa** [comment]
Glad it helped @Weilin37 :smile: 

I'll close this for now but feel free to reopen, create a new issue or come to https://gitter.im/csgodemos/demo-minifier for a chat :slightly_smiling_face:
