### ISSUE TITLE
Output doesn't provide `Player.ViewDirectionY` (pitch)

### ISSUE THREAD

**Issue by d4rwel** [markus-wa/cs-demo-minifier#24]
The output only provides `Player.ViewDirectionX` (yaw) in the field `angle`. But to be able to calculate crosshair placement both view directions (yaw and pitch) are needed. Is it possible to retain this information as well?

**Comment by markus-wa** [comment]
v0.3.0 now contains both `angleX` and `angleY`: https://github.com/markus-wa/cs-demo-minifier/releases/tag/v0.3.0

hope this does the trick.
